### ISSUE TITLE
Issue 1.1 Package does not build - static_obstacle_orca branch

### ISSUE THREAD

**Issue by KavitShah1998** [KavitShah1998/DynamicObstacleAvoidance#1]
On running '**catkin_make**' or '**catkin_make clean**', I get this error

* fatal error: orca_msgs/Vector2.h: No such file or directory*

In my view the error is due to incorrect file inclusions order in CMakeLists.txt of either the orca_msgs package or orca package.

**Comment by KavitShah1998** [comment]
The issue was due to missing add_dependencies tag for the test_sim executable in the orca package's CMakeLists.txt.
This line is essential if you are building the project with a custom defined ROS message.

The issue has been solved in Update 1.3 & thus is being closed

**Comment by wzy012** [comment]
hi, I ran your program and found a problem: 
roslaunch env turtlebot3_env_open_spaces_wwh-edit.launch
... logging to /home/sucro/.ros/log/81b7e430-a10f-11eb-9e8d-9cb6d068dfb9/roslaunch-sucro-GT62VR-7RE-11313.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
Resource not found: person
ROS path [7]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

I looked the file:turtlebot3_env_open_spaces_wwh-edit.launch,and I think the reason for the above problem is: 

  <include file="$(find person)/launch/spawn_walking_person.launch">
    <arg name="x" default="3.0" />
    <arg name="y" default="3.0" />
    <arg name="z" default="0.0" />
    <arg name="yaw" default="-1.570" />
    <arg name="robot_name" default="walking_human_01" />
  </include>

I looked your code,it don't have the "person" file.
Can you help me?Thanks!

**Comment by wzy012** [comment]
hi, I ran your program and found a problem: 
roslaunch env turtlebot3_env_open_spaces_wwh-edit.launch
... logging to /home/sucro/.ros/log/81b7e430-a10f-11eb-9e8d-9cb6d068dfb9/roslaunch-sucro-GT62VR-7RE-11313.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
Resource not found: person
...
ROS path [7]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

I looked the file:turtlebot3_env_open_spaces_wwh-edit.launch,and I think the reason for the above problem is: 

  <include file="$(find person)/launch/spawn_walking_person.launch">
    <arg name="x" default="3.0" />
    <arg name="y" default="3.0" />
    <arg name="z" default="0.0" />
    <arg name="yaw" default="-1.570" />
    <arg name="robot_name" default="walking_human_01" />
  </include>

I looked your code,it don't have the "person" file.
Can you help me?Thanks!

**Comment by KavitShah1998** [comment]
Hi @wzy012,

Thank you for reporting the issue. 

The "person" package has been added. You should be able to run it smoothly once you take a fresh pull.

Best,
@KavitShah1998

**Comment by wzy012** [comment]
> Hi @wzy012,
> 
> Thank you for reporting the issue. 
> 
> The "person" package has been added. You should be able to run it smoothly once you take a fresh pull.
> 
> Best,
> @KavitShah1998 

Thanks!
I will you so late!
Have fun!
